
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


//import ChatClient2;

/**
 *
 * @author Ricky K
 */
public class Login extends javax.swing.JFrame {
    public int benar = 0;
    private ArrayList<DataClient> users = new ArrayList<DataClient>();
    private DataSql client = new DataSql();
  
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //us_address.setVisible(false);
        //address.setVisible(false);
       // btn_host.setVisible(false);
        
        Object data[] = client.getAllData();
        for(int i=0;i<data.length;i++)
        {
            DataClient data1 = (DataClient) data[i];
            users.add(new DataClient(data1.getId(),data1.getPassword(),data1.getNama_barang(),data1.getKelamin(),data1.getStatus()));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        us_name = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        us_password = new javax.swing.JPasswordField();
        Username2 = new javax.swing.JLabel();
        us_address = new javax.swing.JTextField();
        b_send = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.orange);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Username.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        Username.setText("Username");

        address.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        address.setText("Address");

        Username2.setFont(new java.awt.Font("Felix Titling", 1, 14)); // NOI18N
        Username2.setText("Password");

        us_address.setText("localhost");
        us_address.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                us_addressMouseClicked(evt);
            }
        });
        us_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                us_addressActionPerformed(evt);
            }
        });

        b_send.setBackground(java.awt.Color.orange);
        b_send.setText("Submit");
        b_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(us_address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(us_password, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Username, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(us_name, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_send, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(us_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username2)
                .addGap(1, 1, 1)
                .addComponent(us_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(us_address, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_send, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jLabel2.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        jLabel2.setText("Forgot password ?");

        jLabel3.setFont(new java.awt.Font("Felix Titling", 0, 11)); // NOI18N
        jLabel3.setText("Sign up here !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sendActionPerformed
        String User = us_name.getText();
        String Passi = String.valueOf(us_password.getPassword());
        int Pass = Integer.parseInt(Passi);
        int ada = 0;
        if(benar==0)
        {
            for(int i=0;i<users.size();i++)
            {
                String coba = users.get(i).getNama_barang();
                int pas = users.get(i).getPassword();
                int status = users.get(i).getStatus();
                //System.out.println(coba);
                //System.out.println(pas);
                if(User.equals(coba)&&Pass==pas)
                {
                    if(status==0)
                    {
                        client.updateStatus(1, coba);          
                        ada = 0;
                        ChatClient2 d = new ChatClient2();
                        d.usernameTextField.setText(us_name.getText());
                        d.portTextField.setText("2222");
                        d.serverTextField.setText(us_address.getText());
                        d.btn_masukiActionPerformed(evt);
                        if(users.get(i).getKelamin().equals("L"))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Silahkan Masuk Mr."+users.get(i).getNama_barang(),"Warning!!",JOptionPane.INFORMATION_MESSAGE);
                            d.User.setText("Mr. "+us_name.getText());
                            d.setVisible(true);
                            dispose();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, "Silahkan Masuk Ms."+users.get(i).getNama_barang(),"Warning!!",JOptionPane.INFORMATION_MESSAGE);
                            d.User.setText("Ms. "+us_name.getText());
                            d.setVisible(true);
                            dispose();
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Akun Anda Sedang Digunakan!!");
                    }
                    i=users.size();
                }
                else if(User.equals(coba))
                {
                    if(Pass!=pas)
                    {
                        ada = 1;
                    }
                    i = users.size();
                }
                else if(!User.equals(coba))
                {
                    ada = 2;
                   // JOptionPane.showMessageDialog(rootPane, "Username Anda Tidak Ada!!");
                }
                else
                {
                    ada = 3;
                }
            }
        }
        else
        {
            for(int i=0;i<users.size();i++)
            {
                String coba = users.get(i).getNama_barang();
                int pas = users.get(i).getPassword();
     
                if(User.equals(coba)&&Pass==pas)
                {
                    if(users.get(i).getStatus()==0)
                    {
                        client.updateStatus(1, coba);
                        JOptionPane.showMessageDialog(rootPane, "Silahkan Masuk Mr."+users.get(i).getNama_barang(),"Warning!!",JOptionPane.INFORMATION_MESSAGE);
                        ada = 0;
                        ChatClient d = new ChatClient();
                        d.usernameTextField.setText(us_name.getText());
                        d.portTextField.setText("2222");
                        d.serverTextField.setText(us_address.getText());
                        d.btn_masukActionPerformed(evt);
                        if(users.get(i).getKelamin().equals("L"))
                        {
                            d.User.setText("Mr. "+us_name.getText());
                            d.setVisible(true);
                            dispose();
                        }
                        else
                        {
                            d.User.setText("Ms. "+us_name.getText());
                            d.setVisible(true);
                            dispose();
                        }
                        
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Akun Anda Sedang Digunakan!!");
                    }
                    i=users.size();
                    
                }
                else if(User.equals(coba))
                {
                    if(Pass!=pas)
                    {
                        ada = 1;
                    }
                    i = users.size();
                }
                else
                {
                    ada = 2;
                   // JOptionPane.showMessageDialog(rootPane, "Username Anda Tidak Ada!!");
                }
            }
//            ChatClient d = new ChatClient();
//            d.usernameTextField.setText(us_name.getText());
//            d.portTextField.setText("2222");
//            d.serverTextField.setText(us_address.getText());
//            d.btn_masukActionPerformed(evt);
//            d.User.setText("Mr. "+us_name.getText());
//            d.setVisible(true);
        }
        if(ada==1)
            JOptionPane.showMessageDialog(rootPane, "Password Anda Salah!!");
        else if(ada==2)
            JOptionPane.showMessageDialog(rootPane, "Username Anda Tidak Ada!!");
        //us_address.setVisible(true);
        //address.setVisible(true);
        //us_address.setText("localhost");
       // btn_host.setVisible(true);
        
    }//GEN-LAST:event_b_sendActionPerformed

    private void us_addressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_us_addressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_us_addressMouseClicked

    private void us_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_us_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_us_addressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username2;
    private javax.swing.JLabel address;
    private javax.swing.JButton b_send;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField us_address;
    private javax.swing.JTextField us_name;
    private javax.swing.JPasswordField us_password;
    // End of variables declaration//GEN-END:variables

    private int parseInt(char[] password) {
        int hasil = parseInt(password);
        return hasil;
    }
}
